---
# tasks file for pbm
- name: include tasks for test env setup
  include_tasks: ../../../tasks/test_prep.yml

- name: download newer percona-release script
  get_url:
    url: https://raw.githubusercontent.com/EvgeniyPatlan/percona-repositories/master/scripts/percona-release.sh
    dest: /usr/bin/percona-release
    mode: '755'
    force: true


#- name: install Percona repository package on debian/ubuntu
#  apt:
#    deb: https://repo.percona.com/apt/pool/testing/p/percona-release/percona-release_1.0-14.generic_all.deb
#  when: ansible_os_family == "Debian"
#
#- name: install Percona repository package on centos
#  yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm
#  when: ansible_os_family == "RedHat"

- name: enable pdmdb repo
  command: percona-release enable pdmdb-4.2.2 {{ repo }}
  vars:
    repo: "{{ lookup('env', 'install_repo') }}"

- name: clean and update yum cache
  shell: |
    yum clean all
    yum makecache
  when: ansible_os_family == "RedHat"


- name: include tasks for PSMDB 4.2 install
  include_tasks: install_psmdb_full.yml
  when: lookup('env', 'psmdb_to_test') == "psmdb42"


- name: stop mongod service
  service: name=mongod state=stopped

- name: add replica set name into mongod config
  replace:
    path: /etc/mongod.conf
    regexp: '^#replication:'
    replace: 'replication:\n  replSetName: "rs1"'

- name: start mongod service
  service: name=mongod state=started

- name: initiate mongod replica set
  command: mongo --eval 'rs.initiate()'

- name: install PBM new deb packages
  apt:
    name: percona-backup-mongodb
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"

- name: install PBM new rpm packages
  yum:
    name: percona-backup-mongodb
    state: latest
  when: ansible_os_family == "RedHat"

- name: add storage for pbm-agent
  blockinfile:
    path: /etc/pbm-agent-storage.conf
    create: true
    block: |
      storage:
        type: s3
        s3:
           region: us-east-1
           bucket: operator-testing
           credentials:
             access-key-id: {{ access_key }}
             secret-access-key: {{ access_secret }}
  vars:
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    access_secret: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

- name: edit pbm-agent service config for deb
  blockinfile:
    path: /etc/default/pbm-agent
    block: |
      PBM_MONGODB_URI="mongodb://localhost:27017/"
  when: ansible_os_family == "Debian"

- name: edit pbm-agent service config for rhel based
  blockinfile:
    path: /etc/sysconfig/pbm-agent
    block: |
      PBM_MONGODB_URI="mongodb://localhost:27017/"
  when: ansible_os_family == "RedHat"

- name: start pbm-agent service
  service:
    name: pbm-agent
    state: started
    enabled: yes
