---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: rhel-86-${BUILD_NUMBER}-${JOB_NAME}
    region: us-west-2
    image: ami-09798faf8a4db186e
    vpc_subnet_id: subnet-03136d8c244f56036
    instance_type: t2.medium
    ssh_user: ec2-user
    root_device_name: /dev/xvda
    instance_tags:
      iit-billing-tag: pxb-rhel-binary-tarball
      job-name: ${JOB_NAME}
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../playbooks/create.yml
    destroy: ../../../playbooks/destroy.yml
    cleanup: ../../playbooks/cleanup.yml
    converge: ../../playbooks/playbook.yml
scenario:
  name: rhel-86
  destroy_sequence:
    - destroy
  clenup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - cleanup
    - destroy

