---
# tasks file for ps-80-maj-upgrade-to
# This playbook install Percona Server 5.7 with TokuDB and MyRocks
# It will disable the original repo and upgrade to Percona Server 8.0

  - name: install PS 5.7
    include_tasks: ../../ps-57-install/tasks/main.yml

  - name: get my.cnf stats
    stat: path=/etc/my.cnf
    register: mycnf

  - name: copy config file to backup
    copy:
      src: /etc/my.cnf
      dest: /etc/my.cnf.backup
      remote_src: yes
    when: mycnf.stat.exists and ansible_os_family == "RedHat"

  - name: disable all percona repos
    command: percona-release disable all

  - name: remove PXB 2.4 packages
    include_tasks: ../../../tasks/remove_pxb24.yml

  - name: remove PS 5.7 packages
    include_tasks: ../../../tasks/remove_ps57.yml

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - name: check /var/lib/mysql exists and not empty
    fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000

  - name: include tasks for enabling PS 8 test repo
    include: ../../../tasks/enable_ps8_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling PS 8 test repo
    include: ../../../tasks/enable_ps8_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: install Percona Server 8.0 packages
    include_tasks: ../../../tasks/install_ps80.yml

  - name: install PXB 8.0 packages
    include_tasks: ../../../tasks/install_pxb80.yml

  - name: install percona-mysql-shell package
    include_tasks: ../../../tasks/install_pshell.yml

  - name: check that Percona XtraBackup version is correct
    command: /package-testing/version_check.sh pxb80
    when: lookup('env', 'install_repo') != "experimental"

  - name: list installed packages
    include_tasks: ../../../tasks/list_installed_packages.yml

  - name: start mysql service
    service: name=mysql state=started

  - name: check that Percona Server version is correct
    command: /package-testing/version_check.sh ps80

  - name: check that Percona Server package versions are correct
    command: /package-testing/package_check.sh ps80

  - name: run some MyRocks tests
    command: /package-testing/scripts/ps_myrocks_test.sh

#  - name: run bats tests for PAM
#    command: /usr/local/bin/bats /package-testing/scripts/ps_pam_test/ps_pam_test.bats

  - name: keyring plugins test
    command: /package-testing/scripts/ps_keyring_plugins_test/ps_keyring_plugins_test.sh ps80

#  - name: run bats unit tests for ps-admin script
#    command: /usr/local/bin/bats /package-testing/bats/ps-admin_unit.bats

#  - name: run bats integration tests for ps-admin script
#    command: /usr/local/bin/bats /package-testing/bats/ps-admin_integration.bats

  - name: run bats tests for mysql init scripts
    command: /usr/local/bin/bats /package-testing/bats/mysql-init-scripts.bats
