---
# tasks file for psmdb36-upgrade
- name: include tasks for test env setup
  include_tasks: ../../../tasks/test_prep.yml

- name: copy certificate for keyring vault
  copy:
    src: "{{ vault_cert }}"
    dest: /package-testing/scripts/psmdb_encryption/test.cer

- name: create token file for vault
  copy:
    dest: "/package-testing/scripts/psmdb_encryption/mongodb-test-vault-token"
    content: |
      {{ vault_token }}

#
# Install from main repository
#
- name: include tasks for enabling main repo
  include_tasks: ../../../tasks/enable_main_repo.yml

- name: install Percona Server for MongoDB 3.6 deb packages previous version
  apt: name={{item}} update_cache=yes state=latest
  with_items:
  - percona-server-mongodb-36
  - percona-server-mongodb-36-dbg
  when: ansible_os_family == "Debian"

- name: install Percona Server for MongoDB 3.6 new rpm packages previous version
  yum: name={{item}} state=latest
  with_items:
  - Percona-Server-MongoDB-36
  - Percona-Server-MongoDB-36-debuginfo
  when: ansible_os_family == "RedHat"

- name: start mongod with init script
  command: /etc/init.d/mongod start
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: start mongod with systemctl
  command: systemctl start mongod
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

#
# Enable testing repository
#
- include: ../../../tasks/enable_testing_repo.yml

#
# Upgrade packages
#
- name: upgrade Percona Server for MongoDB 3.6 packages
  include_tasks: ../tasks/install_psmdb_36_full.yml

#- name: check that PSMDB 3.6 package versions are correct
#  command: /package-testing/package_check.sh psmdb36
#
#- name: check that PSMDB 3.6 version is correct
#  command: /package-testing/version_check.sh psmdb36
#
#- name: test SE change, import data, restart service
#  command: /package-testing/scripts/psmdb_test.sh 3.6
#
#- name: test encryption with keyfile
#  command: /package-testing/scripts/psmdb_encryption/psmdb-encryption-test.sh keyfile
#
#- name: test encryption with vault
#  command: /package-testing/scripts/psmdb_encryption/psmdb-encryption-test.sh vault
#
#- name: set pass and enable auth
#  command: /package-testing/scripts/psmdb_set_auth.sh
#
#- name: run bats tests for mongo init scripts
#  command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats
#
#- name: install numactl package
#  include_tasks: ../tasks/install_numactl.yml
#
#- name: run bats tests for mongo init scripts
#  command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats
#
#- name: start mongod service
#  service: name=mongod state=started

