---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Percona Server deb packages
      apt:
        name: "{{ packages }}"
        update_cache: no
        state: absent
      vars:
        packages:
        - percona-server-server*
        - percona-xtrabackup-80
      when: ansible_os_family == "Debian"

    - name: remove Percona Server rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
       packages:
        - percona-server-server*
        - percona-xtrabackup-80
      when: ansible_os_family == "RedHat"

    - name: check if process is stopped after package removal
      command: /package-testing/check_running.sh mysql stopped
