
  - name: include playbook for removing Percona repo
    include: remove_percona_repository.yml

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_0.1-10.{{ansible_lsb.codename}}_all.deb
    when: ansible_os_family == "Debian"

  - name: add the main Percona yum repos for centos 6 and 7
#   yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    yum: name=https://repo.percona.com/yum/testing/7Server/RPMS/noarch/percona-release-0.1-10.noarch.rpm
    when: ansible_os_family == "RedHat" 

  - name: enable main repo
    command: percona-release enable original
