  - name: include playbook for removing Percona repo
    include: remove_percona_repository.yml

  - name: Install percona repository package for deb based distros
    apt:
     #deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
      deb: https://repo.percona.com/percona/apt/pool/testing/p/percona-release/percona-release_1.0-23.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: Install percona repository package for rpm based distros
   #yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    yum: name=https://repo.percona.com/percona/yum/testing/8/RPMS/noarch/percona-release-1.0-23.noarch.rpm
    when: ansible_os_family == "RedHat"

  - name: enable {{ psmdb_repo }} repo
    command: percona-release enable-only {{ psmdb_repo }}

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
    when: ansible_os_family == "RedHat"
