- name: Install Percona XtraBackup new DEB packages for pxb-{{ major_release_version_register.stdout }}
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - "percona-xtrabackup-{{ major_release_version_register.stdout }}"
      - "percona-xtrabackup-test-{{ major_release_version_register.stdout }}"
      - "percona-xtrabackup-dbg-{{ major_release_version_register.stdout }}"
  when: ansible_os_family == "Debian"

- name: Install Percona XtraBackup new RPM packages for pxb-{{ major_release_version_register.stdout }}
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - "percona-xtrabackup-{{ major_release_version_register.stdout }}"
      - "percona-xtrabackup-test-{{ major_release_version_register.stdout }}"
      - "percona-xtrabackup-{{ major_release_version_register.stdout }}-debuginfo"
  when: ansible_os_family == "RedHat"
