# install Percona Server for MongoDB 6.0
#
- name: enable psmdb repo
  include_tasks: ./enable_repo.yml
  vars:
    package: "psmdb-60"
    repository: "release"

- name: install psmdb deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - percona-server-mongodb=6.0*
      - percona-server-mongodb-server=6.0*
      - percona-server-mongodb-mongos=6.0*
      - percona-server-mongodb-tools=6.0*
      - percona-server-mongodb-dbg=6.0*
      - percona-mongodb-mongosh
  when: ansible_os_family == "Debian"

- name: install psmdb rpm packages on RedHat 7(and lower)
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - percona-server-mongodb-6.0*
      - percona-server-mongodb-server-6.0*
      - percona-server-mongodb-mongos-6.0*
      - percona-server-mongodb-tools-6.0*
      - percona-mongodb-mongosh
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version <= "7"

- name: install psmdb rpm packages on RedHat 8+
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - percona-server-mongodb-6.0*
      - percona-server-mongodb-server-6.0*
      - percona-server-mongodb-mongos-6.0*
      - percona-server-mongodb-tools-6.0*
      - percona-mongodb-mongosh
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"
