# This task contains common actions for the PMM Client all tests at preparation stage

- name: Install EPEL and GPG
  include_tasks: ./install_epel.yml

- name: allow release-info to change for apt repositories
  command: apt-get update -y --allow-releaseinfo-change
  when: ansible_os_family == "Debian" and ansible_distribution_release == "buster"

- name: install needed packages for running tests with apt
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - unzip
      - wget
      - gnupg
      - rsync
      - jq # for exporter endpoint metric fetch
      - acl
  retries: 60
  delay: 10
  register: result
  until: result is not failed
  when: ansible_os_family == "Debian"

- name: install needed packages for running tests with yum
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - pv
      - libselinux-python
      - unzip
      - wget
      - rsync
      - jq # for exporter end point metric fetch
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 7

- name: install needed packages for running tests with yum on RHEL 8+
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - unzip
      - wget
      - jq # for exporter end point metric fetch
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8

- name: include tasks for enabling test repo
  include_tasks: ./enable_testing_repo.yml
  when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

- name: include tasks for enabling experimental repo
  include_tasks: ./enable_experimental_repo.yml
  when: lookup('env', 'install_repo') == "experimental"

- name: include tasks for enabling main repo
  include_tasks: ./enable_main_repo.yml
  when: lookup('env', 'install_repo') == "main"

- name: include tasks for enabling tools main repo
  include_tasks: ./enable_tools_main_repo.yml
  when: lookup('env', 'install_repo') == "tools-main"

- name: include tasks for enabling experimental repo
  include_tasks: ./enable_pmm2client_main_repo.yml
  when: lookup('env', 'install_repo') == "pmm2-client-main"
