# This task performs PMM Client version verification from "pmm-admin --version" output
#
# Task adjustments are handled by parent playbook vars:
#             var "port_flag"      :  to access agent with custom port
#                                     ex: port_flag: "--pmm-agent-listen-port={{ custom_port }}"

- name: set empty port_flag
  set_fact:
    port_flag: ""
  when: port_flag is not defined

- name: Grep PMM Admin version from pmm-admin --version output
  shell: "pmm-admin --version ${port_flag} 2>&1|grep ^Version | awk -F ' ' '{print $2}'"
  register: pmm_client_version

- name: Print the PMM Server Version on Status command
  ansible.builtin.debug:
    msg: PMM Admin version is {{ pmm_client_version.stdout }}

- name: Assert PMM Admin version from "--version" output ({{ pmm_client_version.stdout }}) equals expected "{{ pmm_version }}"
  assert:
    that:
      - "'{{ pmm_version }}' in pmm_client_version.stdout"
