# Performs PMM Server version verification from "pmm-admin status" output
#
# Task adjustments are handled by parent playbook vars:
#             var "port_flag"      :  to access agent with custom port
#                                     ex: port_flag: "--pmm-agent-listen-port={{ custom_port }}"
#
- name: set empty port_flag
  when: port_flag is not defined
  set_fact:
    port_flag: ""

- name: Grep pmm-admin status output
  shell: "pmm-admin status {{ port_flag }}"
  register: pmm_admin_status

- name: Grep PMM Server version from pmm-admin status output
  shell: "echo \"{{ pmm_admin_status.stdout }}\" | grep Version | awk -F':' '{print $2}' | awk -F' ' '{print $1}'"

  register: pmm_server_version

- name: Print the PMM Server Version on Status command
  ansible.builtin.debug:
    msg: PMM Server version is {{ pmm_server_version.stdout }}

- name: Assert PMM Server version from "status" output ({{ pmm_server_version.stdout }}) equals expected "{{ pmm_version }}"
  assert:
    that:
      - "pmm_version in pmm_server_version.stdout"
    fail_msg: "pmm-agent is not connected to server!"
    success_msg: "pmm-agent is connected to server"