---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: ${PLATFORM}
    region: ${AWS_DEFAULT_REGION}
    image: ${IMAGE}
    vpc_subnet_id: ${SUBNET}
    instance_type: ${INSTANCE_TYPE}
    ssh_user: ${USER}
    root_device_name: ${ROOT_DEVICE_NAME}
    instance_tags:
      iit-billing-tag: jenkins-pg-worker
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
    enabled: False
  playbooks:
    create: ../../playbooks/create.yml
    destroy: ../../playbooks/destroy.yml
    prepare: ../../playbooks/prepare.yml
instances:
  - name: pg-11
verifier:
  name: testinfra
  options:
    verbose: true
    s: true
    junitxml: report.xml
  lint:
    name: flake8
    enabled: False
scenario:
  name: pg-11
  destroy_sequence:
    - destroy
  clenup_sequence:
    - cleanup
  test_sequence:
    - lint
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - cleanup
    # - side_effect
    - destroy
