---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: disable all percona repos
    command: percona-release disable all

  - name: remove Percona Server deb packages
    apt:
      name: "{{ packages }}"
      update_cache: no
      state: absent
    vars:
      packages:
      - percona-server-server
      - percona-server-test
      - percona-server-dbg
      - percona-server-source
      - percona-server-client
      - percona-server-tokudb
      - percona-server-rocksdb
    when: ansible_os_family == "Debian"

  - name: remove Percona Server rpm packages
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
     packages:
      - percona-server-server
      - percona-server-client
      - percona-server-test
      - percona-server-debuginfo
      - percona-server-devel
      - percona-server-tokudb
      - percona-server-rocksdb
    when: ansible_os_family == "RedHat"

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000

#    - name: Unregister RedHat
#      redhat_subscription:
#        state: absent
#      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
