---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: get my.cnf stats
    stat: path=/etc/my.cnf
    register: mycnf

  - name: copy config file to backup
    copy:
      src: /etc/my.cnf
      dest: /etc/my.cnf.backup
      remote_src: yes
    when: mycnf.stat.exists and ansible_os_family == "RedHat"

  - name: disable all percona repos
    command: percona-release disable all

  - name: remove PXB 2.4 packages
    include_tasks: ../../../../tasks/remove_pxb24.yml

  - name: remove PS 5.6 packages
    include_tasks: ../../../../tasks/remove_ps56.yml

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - name: check /var/lib/mysql exists and not empty
    fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000

#    - name: Unregister RedHat
#      redhat_subscription:
#        state: absent
#      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
