---
# tasks file for tarball tests

  - name: Display OS Name
    debug:
      msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"


  - name: Add epel-release
    yum:
      state: present
      name: epel-release
    when: ansible_os_family == "RedHat" and ansible_distribution_version != "2023"

  - name: install needed packages for running tests with apt
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - git
      - unzip
      - wget
      - python3
      - python3-pip
      - libnuma1
      - tar
      - gawk
      - libtirpc3
    register: result
    until: result is not failed
    when: ansible_os_family == "Debian"

  - name: install libaio1 package for running tests with apt except for Ubuntu 24.04
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - libaio1 
    register: result
    until: result is not failed
    when: ansible_os_family == "Debian" and  ansible_distribution_version not in ["24.04"] 

  - name: install needed packages for running tests with yum
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - git
      - unzip
      - wget
      - tar
      - libaio
      - numactl
      - gawk
      - python3
      - python3-pip
      - libtirpc
      - lsb_release
    when: ansible_os_family == "RedHat" and ansible_distribution_version != "2023"


#      - openldap // this package causes issue on OL-9

  - name: get GLIBC_VERSION
    set_fact:
      GLIBC_VERSION: "{{ '2.31' if ansible_os_family == 'Debian' else '2.28' }}"
#
  - name: Set full and short ProxySQL versions
    set_fact:
      proxysql_folder_version: "{{ lookup('env', 'PROXYSQL_VERSION').split('-')[0] }}"

  - name: Set tarball name and folder name
    set_fact:
      tarball_name: "proxysql-{{ proxysql_folder_version }}-Linux-x86_64.glibc{{ GLIBC_VERSION }}.tar.gz"
      tarball_folder: "proxysql-{{ proxysql_folder_version }}-Linux-x86_64.glibc{{ GLIBC_VERSION }}"


  - name: Show constructed URL and filename
    debug:
     msg: |
        Tarball name: {{ tarball_name }}
        Folder: {{ tarball_folder }}
        URL: https://downloads.percona.com/downloads/TESTING/proxysql-{{ proxysql_folder_version }}/{{ tarball_name }}

  - name: Ensure /package-testing/proxysql directory exists
    file:
      path: /package-testing/proxysql
      state: directory
      mode: '0755'

  - name: Download ProxySQL tarball
    ansible.builtin.get_url:
      url: "https://downloads.percona.com/downloads/TESTING/proxysql-{{ proxysql_folder_version }}/{{ tarball_name }}"
      dest: "/package-testing/proxysql/{{ tarball_name }}"
      mode: '0644'

  - name: Extract ProxySQL tarball
    ansible.builtin.unarchive:
      src: "/package-testing/proxysql/{{ tarball_name }}"
      dest: "/package-testing/proxysql/"
      remote_src: yes


  - name: Print contents of extracted folder
    command: ls -l /package-testing/proxysql/{{ tarball_folder }}
    register: extracted_list


  - name: Show extracted contents
    debug:
     msg: "{{ extracted_list.stdout_lines }}"
     
  - name: download package-testing repo branch with wget
    command: "{{ item }}"
    with_items:
    - rm -rf package-testing
    - rm -f master.zip
    - wget --no-check-certificate -O master.zip "https://github.com/{{ git_account }}/package-testing/archive/{{ branch }}.zip"
    - unzip master.zip
    - rm -f master.zip
    - mv "package-testing-{{ branch }}" package-testing
    vars:
      branch: "{{ lookup('env', 'TESTING_BRANCH') | default('PXC-FINAL') }}"
      git_account: "{{ lookup('env', 'TESTING_GIT_ACCOUNT') | default('Grishma123-Eng', true) }}"

  - name: Append values to /etc/environment file
    lineinfile:
      path: /etc/environment
      line: "{{ item }}"
      state: present
    with_items:
    - "PROXYSQL_VERSION={{ lookup('env', 'PROXYSQL_VERSION') }}"
    - "REVISION={{ lookup('env', 'REVISION') }}"
    - "TARBALL_NAME={{ tarball_name }}"
