---
# tasks file for pdmysql-pxb
- name: include tasks for test env setup
  include_tasks: ../../../tasks/test_prep.yml

- name: include tasks for enabling main repo
  include: ../../pdmysql_tasks/enable_original_repo.yml
  when: lookup('env', 'REPO') == "main"

- name: include tasks for enabling PDMYSQL PS 8 test repo
  include: ../../pdmysql_tasks/enable_main_repo.yml
  when: lookup('env', 'REPO') == "main"

- name: include tasks for enabling PS 8 test repo
  include: ../../pdmysql_tasks/enable_testing_repo.yml
  when: lookup('env', 'REPO') == "testing" or lookup('env', 'REPO') == ""

- name: include tasks for enabling PS 8 experimental repo
  include: ../../pdmysql_tasks/enable_experimental_repo.yml
  when: lookup('env', 'REPO') == "experimental"

- name: download and extract world database
  command: "{{ item }}"
  with_items:
  - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

- name: install Percona Toolkit new deb packages
  include_tasks: ../../../tasks/install_pt.yml

- name: install Percona Server 8.0 packages
  include_tasks: ../../../tasks/install_ps80.yml

- name: install Percona XtraBackup 8.0 packages
  include_tasks: ../../../tasks/install_pxb80.yml

- name: start mysql service with service command
  command: service mysql start
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: start mysql service with systemctl command
  command: systemctl start mysql
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

- name: set root password on centos
  command: /package-testing/setpass_57.sh
  when: ansible_os_family == "RedHat"

- name: install plugins, import world database
  command: /package-testing/plugins_test.sh

- name: check that Percona Toolkit version is correct
  command: /package-testing/version_check.sh pt

- name: check that Percona XtraBackup version is correct
  command: /package-testing/version_check.sh pxb80

- name: check that Percona XtraBackup package versions are correct
  command: /package-testing/package_check.sh pxb80

#- name: run backup
#  command: /usr/bin/xtrabackup --backup --user=root --target-dir=/tmp/backups/
#
#- name: prepare backup
#  command: /usr/bin/xtrabackup --prepare --user=root --target-dir=/tmp/backups/


