---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Percona Server for MongoDB 4.0 deb packages
      apt:
        name: "{{ packages }}"
        update_cache: no
        state: absent
      vars:
        packages:
        - percona-server-mongodb-server
      when: ansible_os_family == "Debian"

    - name: remove Percona Server for MongoDB 4.0 rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - percona-server-mongodb-server
      when: ansible_os_family == "RedHat"

    - name: check if process is stopped after package removal
      command: /package-testing/check_running.sh mongodb stopped
