---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: debian9-${BUILD_NUMBER}-${JOB_NAME}
    region: us-west-2
    image: ami-01d07e14f082b3ba1
    vpc_subnet_id: subnet-024be5829372c4f38f
    instance_type: t2.micro
    ssh_user: admin
    root_device_name: xvda
    instance_tags:
      iit-billing-tag: jenkins-ps80-worker
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../../playbooks/prepare.yml
    cleanup: ../../playbooks/cleanup.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: testinfra
  directory: ../tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
  additional_files_or_dirs:
    - ../../../tests/test_proxysql2.py
    - ../../../tests/test_pxb.py
    - ../../../tests/test_sources.py
scenario:
  name: debian-9
  destroy_sequence:
    - destroy
  clenup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
