---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove percona release deb package
      apt:
        name: percona-release
        state: absent
      when: ansible_os_family == "Debian"
    - name: remove percona release rpm package
      yum:
        name: percona-release
        state: absent
      when: ansible_os_family == "RedHat"
