---
scenario:
  name: centos-6
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: pxc2-56-common-centos-6
    region: us-west-2
    image: ami-0362922178e02e9f3
    vpc_subnet_id: subnet-0430e63d7cdbcd237
    instance_type: t2.micro
    ssh_user: centos
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pxc-worker
  - name: pxc3-56-common-centos-6
    region: us-west-2
    image: ami-0362922178e02e9f3
    vpc_subnet_id: subnet-0430e63d7cdbcd237
    instance_type: t2.micro
    ssh_user: centos
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pxc-worker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create: ../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
  inventory:
    host_vars:
      pxc2-56-common-centos-6:
        ip_env: PXC2_IP
      pxc3-56-common-centos-6:
        ip_env: PXC3_IP
        sleep_before_tests: 40