---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Percona Server for MongoDB 4.2 deb packages
      apt: name={{item}} update_cache=no state=absent
      with_items:
      - percona-server-mongodb-server
      when: ansible_os_family == "Debian"

    - name: remove Percona Server for MongoDB 4.2 rpm packages
      yum: name={{item}} state=absent
      with_items:
      - percona-server-mongodb-server
      when: ansible_os_family == "RedHat"

    - name: check if process is stopped after package removal
      command: /package-testing/check_running.sh mongodb stopped
