---
# tasks file for psmdb40-upgrade
# This tasks does following:
#   sets main Percona repo
#   installs PSMDB 4.0
#   changes repo to testing
#   upgrades packages to the new version
#   does some tests
- name: include tasks for test env setup
  include_tasks: ../tasks/test_prep.yml

- name: copy certificate for keyring vault
  copy:
    src: "{{ vault_cert }}"
    dest: /package-testing/scripts/psmdb_encryption/test.cer

- name: create token file for vault
  copy:
    dest: "/package-testing/scripts/psmdb_encryption/mongodb-test-vault-token"
    content: |
      {{ vault_token }}

#
# Install from main repository
#
- name: include tasks for enabling main repo
  include_tasks: ../tasks/enable_main_repo.yml

- name: include tasks for enabling main repo
  include_tasks: ../tasks/enable_psmdb40_main_repo.yml

- name: install Percona Server for MongoDB 4.0 packages from main repos
  include_tasks: ../tasks/install_psmdb.yml

- name: start mongod with init script
  command: /etc/init.d/mongod start
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: start mongod with systemctl
  command: systemctl start mongod
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 6

#
# Enable testing repository
#
- name: include tasks for enabling test repo
  include_tasks: ../tasks/enable_psmdb40_testing_repo.yml

#
# Upgrade packages
#
- name: upgrade Percona Server for MongoDB 4.0 to new deb packages
  include_tasks: ../tasks/install_psmdb_full.yml

#- name: check that PSMDB 4.0 package versions are correct
#  command: /package-testing/package_check.sh psmdb40
#
#- name: check that PSMDB 4.0 version is correct
#  command: /package-testing/version_check.sh psmdb40
#
#- name: test SE change, import data, restart service
#  command: /package-testing/scripts/psmdb_test.sh 4.0
#
#- name: test encryption with keyfile
#  command: /package-testing/scripts/psmdb_encryption/psmdb-encryption-test.sh keyfile
#
#- name: test encryption with vault
#  command: /package-testing/scripts/psmdb_encryption/psmdb-encryption-test.sh vault
#
#- name: set pass and enable auth
#  command: /package-testing/scripts/psmdb_set_auth.sh
#
#- name: run bats tests for mongo init scripts
#  command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats
#
#- name: install numactl package
#  include_tasks: ../tasks/install_numactl.yml
#
#- name: run bats tests for mongo init scripts
#  command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats
#
#- name: start mongod service
#  service: name=mongod state=started
