---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: rhel10-${BUILD_NUMBER}-${BUILD_NUMBER}-${JOB_NAME}-pxb-tarball
    region: us-west-1
    image: ami-000d4b0de27d4e580
    vpc_subnet_id: subnet-04a8ad1b1d4da874c
    instance_type: t3.micro
    ssh_user: ec2-user
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: pxb-rhel-binary-tarball
      job-name: ${JOB_NAME}
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../playbooks/create.yml
    destroy: ../../playbooks/destroy.yml
    prepare: ../../playbooks/prepare.yml
    cleanup: ../../playbooks/cleanup.yml
    converge: ../../playbooks/playbook.yml
scenario:
  name: rhel-10
  destroy_sequence:
    - destroy
  clenup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    #- verify
    - cleanup
    - destroy
