---
# tasks file for pdmysql-proxysql

- name: Enable repository
  include_tasks: ../../common/enable_repo.yml

- name: install proxysql new deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - proxysql2
  when: ansible_os_family == "Debian"

- name: install proxysql new rpm packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - proxysql2
  when: ansible_os_family == "RedHat"

- name: check that proxysql version is correct
  command: /package-testing/version_check.sh proxysql2

- name: start proxysql service
  service: name=proxysql state=started

- name: stop proxysql service
  service: name=proxysql state=stopped

- name: start proxysql service
  service: name=proxysql state=started
