---
# tasks file for pdmysql-orchestrator
#- name: include tasks for test env setup
#  include_tasks: ../../../tasks/test_prep.yml

- name: Enable repository
  include_tasks: ../../common/enable_repo.yml

- name: install orchestrator new deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-orchestrator-cli
    - percona-orchestrator-client
    - percona-orchestrator
  when: ansible_os_family == "Debian"

- name: install orchestrator new rpm packages
  yum:
    name: percona-orchestrator
    state: latest
  when: ansible_os_family == "RedHat"
