---
scenario:
  name: debian-11
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: pxc2-57-common-debian-11
    region: us-west-2
    image: ami-0362922178e02e9f3
    vpc_subnet_id: subnet-0430e63d7cdbcd237
    instance_type: t2.micro
    ssh_user: centos
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pxc-worker
  - name: pxc3-57-common-debian-11
    region: us-west-2
    image: ami-0362922178e02e9f3
    vpc_subnet_id: subnet-0430e63d7cdbcd237
    instance_type: t2.micro
    ssh_user: centos
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pxc-worker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create: ../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
  inventory:
    host_vars:
      pxc2-57-common-debian-11:
        ip_env: PXC2_IP
      pxc3-57-common-debian-11:
        ip_env: PXC3_IP
        sleep_before_tests: 20