---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Percona Server for MongoDB 4.0 deb packages
      include_tasks: ../tasks/remove_psmdb.yml

    - name: check if process is stopped after package removal
      command: /package-testing/check_running.sh mongodb stopped
