# This task installs Percona Server 8.0 on CentOS and Debian/Ubuntu
#
  - name: disable the mysql module on RHEL/CentOS 8
    command: yum module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - name: disable the mariadb module on RHEL/CentOS 8
    command: yum module disable mariadb -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - name: DNF clean RHEL
    command: sudo dnf clean all -y
    when: ansible_distribution == "RedHat"

  - name: install Percona Server deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-server-server
      - percona-server-test
      - percona-server-dbg
      - percona-server-source
      - percona-server-client
      - percona-server-tokudb
      - percona-server-rocksdb
    when: ansible_os_family == "Debian"

  - name: install Percona Server rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      disablerepo: "epel"
      update_cache: yes
    vars:
      packages:
      - percona-server-server
      - percona-server-client
      - percona-server-test
      - percona-server-debuginfo
      - percona-server-devel
      - percona-server-tokudb
      - percona-server-rocksdb
    when: ansible_os_family == "RedHat"
