  - name: include playbook for removing Percona repo
    include: ../../../tasks/remove_percona_repository.yml

  - name: Install percona release
    include: ../../tasks/install_percona_release.yml

  - name: enable the PDMYSQL-80 main repo
    command: percona-release enable pdpxc-8.0.19 {{ repo }}
    vars:
      repo: "{{ lookup('env', 'REPO') }}"
