---
# tasks file for pbm
#- name: include tasks for test env setup
#  include_tasks: ../../../tasks/test_prep.yml

- name: include tasks for enabling test repo
  include_tasks: ../../../tasks/enable_testing_repo.yml
  when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

- name: include tasks for enabling experimental repo
  include_tasks: ../../../tasks/enable_experimental_repo.yml
  when: lookup('env', 'install_repo') == "experimental"

- name: include tasks for enabling main repo
  include_tasks: ../../../tasks/enable_main_repo.yml
  when: lookup('env', 'install_repo') == "main"

- name: include tasks for enabling tools testing repo
  command: percona-release enable tools testing
  when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

- name: include tasks for enabling tools main repo
  command: percona-release enable tools release
  when: lookup('env', 'install_repo') == "main"

- name: include tasks for enabling tools main repo
  command: percona-release enable tools experimental
  when: lookup('env', 'install_repo') == "experimental"

- name: enable the PSMDB 4.0 testing repo
  command: percona-release enable psmdb-40
  when: lookup('env', 'psmdb_to_test') == "psmdb40"

- name: enable the PSMDB 4.2 testing repo
  command: percona-release enable psmdb-42
  when: lookup('env', 'psmdb_to_test') == "psmdb42"

- name: include tasks for PSMDB 4.0 and 4.2 install
  include_tasks: install_psmdb_full.yml
#  include_tasks: ../../../tasks/install_psmdb_full.yml
  when: lookup('env', 'psmdb_to_test') == "psmdb40" or lookup('env', 'psmdb_to_test') == "psmdb42"

- name: include tasks for PSMDB 3.6 install
  include_tasks: install_psmdb_36_full.yml
#  include_tasks: ../../../tasks/install_psmdb_36_full.yml
  when: lookup('env', 'psmdb_to_test') == "psmdb36"

#- name: include tasks for PSMDB 4.2 install
##  include_tasks: ../../../tasks/install_psmdb_full.yml
#  when: lookup('env', 'psmdb_to_test') == "psmdb42"

- name: stop mongod service
  service: name=mongod state=stopped

- name: add replica set name into mongod config
  replace:
    path: /etc/mongod.conf
    regexp: '^#replication:'
    replace: 'replication:\n  replSetName: "rs1"'

- name: start mongod service
  service: name=mongod state=started

- name: initiate mongod replica set
  command: mongo --eval 'rs.initiate()'

- name: install PBM new deb packages
  apt:
    name: percona-backup-mongodb
    update_cache: yes
    state: latest
  when: ansible_os_family == "Debian"

- name: install PBM new rpm packages
  yum:
    name: percona-backup-mongodb
    state: latest
  when: ansible_os_family == "RedHat"

- name: add storage for pbm-agent
  blockinfile:
    path: /etc/pbm-agent-storage.conf
    create: true
    block: |
      storage:
        type: s3
        s3:
           region: us-east-1
           bucket: operator-testing
           credentials:
             access-key-id: {{ access_key }}
             secret-access-key: {{ access_secret }}
  vars:
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    access_secret: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

- name: add GCP storage for pbm-agent
  blockinfile:
    path: /etc/pbm-agent-storage-gcp.conf
    create: true
    block: |
      storage:
        type: s3
        s3:
           region: us-east-1
           endpointUrl: https://storage.googleapis.com
           bucket: operator-testing
           credentials:
             access-key-id: {{ access_key }}
             secret-access-key: {{ access_secret }}
  vars:
    access_key: "{{ lookup('env', 'GCP_ACCESS_KEY') }}"
    access_secret: "{{ lookup('env', 'GCP_SECRET_KEY') }}"

- name: add local storage for pbm-agent
  blockinfile:
    path: /etc/pbm-agent-storage-local.conf
    create: true
    block: |
      storage:
          type: filesystem
          filesystem:
              path: /tmp

- name: edit pbm-agent service config for deb
  blockinfile:
    path: /etc/default/pbm-agent
    block: |
      PBM_MONGODB_URI="mongodb://localhost:27017/"
  when: ansible_os_family == "Debian"

- name: edit pbm-agent service config for rhel based
  blockinfile:
    path: /etc/sysconfig/pbm-agent
    block: |
      PBM_MONGODB_URI="mongodb://localhost:27017/"
  when: ansible_os_family == "RedHat"

- name: start pbm-agent service
  service:
    name: pbm-agent
    state: started
    enabled: yes
