---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: ${NAME}
    region: eu-central-1
    image: ami-0badcc5b522737046
    vpc_subnet_id: subnet-085deaca8c1c59a4f
    instance_type: t2.micro
    ssh_user: ec2-user
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-pg-worker
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../../../playbooks/create.yml
    destroy: ../../../playbooks/destroy.yml
    prepare: ../../../playbooks/prepare.yml
    cleanup: ../playbooks/cleanup-rpm.yml
verifier:
  name: testinfra
  directory: ../tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
scenario:
  name: rhel8
  destroy_sequence:
    - destroy
  clenup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
