pipeline {
  agent { label 'docker' }
  parameters {
    choice(name: 'DOCKER_ACC', choices: ['percona','perconalab'], description: 'Docker repo to use: percona or perconalab')
    choice(
            choices: ['PS80', 'PS84', 'PS_INN_LTS'],
            description: 'Choose the product version to test',
            name: 'PRODUCT_TO_TEST'
        )
  }
  stages {
    stage('SET PS_VERSION and ROUTER_VERSION') {
        steps {
          script {
            sh '''
              rm -rf /package-testing
              rm -f master.zip
              wget https://github.com/Percona-QA/package-testing/archive/master.zip
              unzip master.zip
              rm -f master.zip
              mv "package-testing-master" package-testing
            '''
                    
            def VERSION = sh(
                script: '''cd package-testing && grep ${PRODUCT_TO_TEST}_VER VERSIONS | awk -F= '{print \$2}' | sed 's/"//g' ''',
                returnStdout: true
                ).trim()

            def REVISION = sh(
                script: '''cd package-testing && grep ${PRODUCT_TO_TEST}_REV VERSIONS | awk -F= '{print \$2}' | sed 's/"//g' ''',
                returnStdout: true
                ).trim()
                    
            // Router version uses the same version as PS
            env.PS_VERSION = "${VERSION}-amd64"
            env.ROUTER_VERSION = "${VERSION}-amd64"
            env.PS_REVISION = "${REVISION}"
            env.DOCKER_ACC = "${DOCKER_ACC}"

            echo "PS_VERSION fetched: ${env.PS_VERSION}"
            echo "ROUTER_VERSION fetched: ${env.ROUTER_VERSION}"
            echo "PS_REVISION fetched: ${env.PS_REVISION}"
            echo "DOCKER_ACC: ${env.DOCKER_ACC}"

          }
       }
     }
    stage('Prepare') {
      steps {
          script {
            currentBuild.displayName = "#${BUILD_NUMBER}-${ROUTER_VERSION}-${PS_REVISION}"
            currentBuild.description = "${DOCKER_ACC}"
          }
         }
        }
    stage("Run parallel") {
        parallel {
      stage ('Run trivy analyzer') {
        steps {
            sh """
              sudo yum install -y curl wget git
              TRIVY_VERSION=\$(curl --silent 'https://api.github.com/repos/aquasecurity/trivy/releases/latest' | grep '"tag_name":' | tr -d '"' | sed -E 's/.*v(.+),.*/\\1/')
              wget https://github.com/aquasecurity/trivy/releases/download/v\${TRIVY_VERSION}/trivy_\${TRIVY_VERSION}_Linux-64bit.tar.gz
              sudo tar zxvf trivy_\${TRIVY_VERSION}_Linux-64bit.tar.gz -C /usr/local/bin/
              wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl
              /usr/local/bin/trivy -q image --format template --template @junit.tpl  -o trivy-hight-junit.xml \
              --timeout 10m0s --ignore-unfixed --exit-code 1 --severity HIGH,CRITICAL ${DOCKER_ACC}/percona-mysql-router:${ROUTER_VERSION}
            """
         } //end steps
         post {
           always {
                    junit testResults: "*-junit.xml", keepLongStdio: true, allowEmptyResults: true, skipPublishingChecks: true
                }
        }
      } //end Run trivy analyzer
     
      stage('Run tests') {
        steps {
            sh '''
              # disable THP on the host for TokuDB
              echo "echo never > /sys/kernel/mm/transparent_hugepage/enabled" > disable_thp.sh
              echo "echo never > /sys/kernel/mm/transparent_hugepage/defrag" >> disable_thp.sh
              chmod +x disable_thp.sh
              sudo ./disable_thp.sh
              # run test
              export PATH=${PATH}:~/.local/bin
              export PS_VERSION=${PS_VERSION}
              export ROUTER_VERSION=${ROUTER_VERSION}
              export PS_REVISION=${PS_REVISION}
              export DOCKER_ACC=${DOCKER_ACC}
              sudo yum install -y python3 python3-pip
              rm -rf package-testing
              git clone https://github.com/Percona-QA/package-testing.git --depth 1
              cd package-testing/docker-image-tests/ps-mysql-router
              pip3 install --user -r requirements.txt
              ./run.sh
            '''
        } //end steps
        post {
          always {
          junit 'package-testing/docker-image-tests/ps-mysql-router/report.xml'
        }
       }
     } //end Run tests
    } //end parallel
   } 
  }
}
