---
# This playbook does following:
#   enables Percona testing repository
#   installs latest version of PS 5.6, PT and PXB 2.3
#   does some tests

# Cosmic is still missing python
- import_playbook: test_prep.yml
- import_playbook: common_56.yml

- hosts: all
  become: true
  become_method: sudo
  vars:
    vault_token: "{{ lookup('env', 'VAULT_TEST_TOKEN') }}"
    vault_cert: "{{ lookup('env', 'VAULT_TEST_CERT') }}"

  tasks:
  - name: remove PS 5.6 packages
    include_tasks: ../tasks/remove_ps56.yml

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000

  - name: copy config file to original location
    copy:
      src: /etc/my.cnf.backup
      dest: /etc/my.cnf
      remote_src: yes
      force: yes
    when: (ansible_distribution == "Amazon") or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7")

  # BUG: PS-3664
  - name: create env file for systemd service
    copy:
      dest: "/etc/sysconfig/mysql"
      content: |
        LD_PRELOAD=/usr/lib64/libjemalloc.so.1 /usr/lib64/mysql/libHotBackup.so
        THP_SETTING=never
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

  - name: setup config file for keyring vault
    template: src=../scripts/ps_keyring_plugins_test/keyring_vault_test.j2
              dest=/package-testing/scripts/ps_keyring_plugins_test/keyring_vault_test.cnf
              mode=0664 owner=root group=root

  - name: copy certificate for keyring vault
    copy:
      src: "{{ vault_cert }}"
      dest: /package-testing/scripts/ps_keyring_plugins_test/test.cer
    when: lookup('env', 'PS_SKIP_KEYRING') == "" or lookup('env', 'PS_SKIP_KEYRING') == "0"

  - name: remove mysql package on centos 8
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - mysql
      - mysql-common
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - name: include tasks for enabling test repo
    include: ../tasks/enable_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling main repo
    include: ../tasks/enable_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling experimental repo
    include: ../tasks/enable_experimental_repo.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: enable tools testing repo
    command: percona-release enable tools testing

  - name: install Percona Server 5.7 packages
    include_tasks: ../tasks/install_ps57.yml

  - name: install Percona Toolkit new deb packages
    include_tasks: ../tasks/install_pt.yml

  - name: install sysbench packages
    include_tasks: ../tasks/install_sysbench.yml
    when: lookup('env', 'install_repo') != "experimental"

  - name: install Percona XtraBackup 2.4 packages
    include_tasks: ../tasks/install_pxb24.yml

  - name: list installed packages
    include_tasks: ../tasks/list_installed_packages.yml

  - name: start mysql service
    service: name=mysql state=started

  - name: run mysql_upgrade
    command: mysql_upgrade -uroot

  - name: restart mysql service
    service: name=mysql state=restarted

  - name: keyring plugins test
    command: /package-testing/scripts/ps_keyring_plugins_test/ps_keyring_plugins_test.sh ps57
    when: lookup('env', 'PS_SKIP_KEYRING') == "" or lookup('env', 'PS_SKIP_KEYRING') == "0"

  - name: run ps_admin to install rocksdb
    command: /usr/bin/ps-admin --enable-rocksdb

  - name: check that Percona Server version is correct
    command: /package-testing/version_check.sh ps57

  - name: check that Percona Server package versions are correct
    command: /package-testing/package_check.sh ps57

  - name: check that Percona Toolkit version is correct
    command: /package-testing/version_check.sh pt
    when: lookup('env', 'install_repo') != "experimental"

# - name: check that sysbench version is correct
#   command: /package-testing/version_check.sh sysbench
#   when: lookup('env', 'install_repo') != "experimental"

  - name: check that Percona XtraBackup version is correct
    command: /package-testing/version_check.sh pxb24
    when: lookup('env', 'install_repo') != "experimental"

  - name: check that Percona XtraBackup package versions are correct
    command: /package-testing/package_check.sh pxb24
    when: lookup('env', 'install_repo') != "experimental"

  - name: remove PS 5.7 packages
    include_tasks: ../tasks/remove_ps57.yml

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - name: check /var/lib/mysql exists and not empty
    fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000
