---
# This playbook does following:
#   enables Percona testing repository
#   installs latest version of PS 5.6, PT and PXB 2.3
#   does some tests

# Cosmic is still missing python
- import_playbook: test_prep.yml

- hosts: all
  become: true
  become_method: sudo
  vars:
    vault_token: "{{ lookup('env', 'VAULT_TEST_TOKEN') }}"
    vault_cert: "{{ lookup('env', 'VAULT_TEST_CERT') }}"

  tasks:
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: include tasks for enabling test repo
    include: ../tasks/enable_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling main repo
    include: ../tasks/enable_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling experimental repo
    include: ../tasks/enable_experimental_repo.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: download and extract world database
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

  - name: install Percona Toolkit new packages
    include_tasks: ../tasks/install_pt.yml

  - name: install sysbench new packages
    include_tasks: ../tasks/install_sysbench.yml

  - name: install PS 5.6 packages
    include_tasks: ../tasks/install_ps56.yml

  - name: install PXB 2.4 packages
    include_tasks: ../tasks/install_pxb24.yml

  - name: list installed packages
    include_tasks: ../tasks/list_installed_packages.yml

  - name: Make sure SELinux is in enforcing mode on CentOS
    selinux:
      policy: targeted
      state: enforcing
    when: ansible_os_family == "RedHat"

  - name: start mysql service with service command
    command: service mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mysql service with systemctl command
    command: systemctl start mysql
    when: (ansible_distribution == "Amazon") or (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")

  - name: disable selinux on centos for TokuDB to work
    command: setenforce 0
    when: ansible_os_family == "RedHat"

  - name: install tokudb and restart server
    command: /usr/bin/ps_tokudb_admin --enable --enable-backup

  - name: restart mysql service
    command: service mysql restart

  - name: re-run ps_tokudb_admin to finish tokudb install
    command: /usr/bin/ps_tokudb_admin --enable --enable-backup

  - name: install plugins, import world database, test tokudb
    command: /package-testing/plugins_test_56.sh ps

  - name: check that Percona Server version is correct
    command: /package-testing/version_check.sh ps56
    when: ansible_os_family == "Debian"

  - name: check that Percona Server package versions are correct
    command: /package-testing/package_check.sh ps56

  - name: check that Percona Toolkit version is correct
    command: /package-testing/version_check.sh pt

#  - name: check that sysbench version is correct
#    command: /package-testing/version_check.sh sysbench

  - name: check that Percona XtraBackup version is correct
    command: /package-testing/version_check.sh pxb24
    when: ansible_os_family == "Debian"

  - name: check that Percona XtraBackup package versions are correct
    command: /package-testing/package_check.sh pxb24
    when: ansible_os_family == "Debian"

  - name: run sysbench prepare script
    command: sysbench --mysql-user=root --mysql-db=sb --time=30 --threads=64 --tables=3 oltp_read_write prepare

  - name: run sysbench benchmark
    command: sysbench --mysql-user=root --mysql-db=sb --time=30 --threads=64 --tables=3 oltp_read_write run

  - name: run sysbench tpcc prepare script
    command: /usr/share/sysbench/tpcc.lua --mysql-user=root --mysql-db=sbt --time=30 --threads=64 --report-interval=1 --tables=3 --scale=5 --db-driver=mysql prepare

  - name: run sysbench tpcc benchmark
    command: /usr/share/sysbench/tpcc.lua --mysql-user=root --mysql-db=sbt --time=30 --threads=64 --report-interval=1 --tables=3 --scale=5 --db-driver=mysql run

  - name: install 3rd party packages with apt
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - rsyslog-mysql
    when: ansible_os_family == "Debian"

  - name: install 3rd party packages with yum
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - rsyslog-mysql
    when: ansible_os_family == "RedHat"

  - name: start mysql service
    service: name=mysql state=started

    # temporary commented out until BLD-906 is resolved
# - name: check that mysqladmin shutdown works correctly
#   command: /package-testing/madmin_check.sh

  - name: remove PS 5.6 packages
    include_tasks: ../tasks/remove_ps56.yml

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000

  - name: copy config file to original location
    copy:
      src: /etc/my.cnf.rpmsave
      dest: /etc/my.cnf
      remote_src: yes
      force: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

  - name: create env file for systemd service
    copy:
      dest: "/etc/sysconfig/mysql"
      content: |
        LD_PRELOAD=/usr/lib64/libjemalloc.so.1
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

  - name: setup config file for keyring vault
    template: src=../scripts/ps_keyring_plugins_test/keyring_vault_test.j2
              dest=/package-testing/scripts/ps_keyring_plugins_test/keyring_vault_test.cnf
              mode=0664 owner=root group=root

  - name: copy certificate for keyring vault
    copy:
      src: "{{ vault_cert }}"
      dest: /package-testing/scripts/ps_keyring_plugins_test/test.cer

  - name: include tasks for enabling test repo
    include: ../tasks/enable_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling main repo
    include: ../tasks/enable_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling experimental repo
    include: ../tasks/enable_experimental_repo.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: enable tools testing repo
    command: percona-release enable tools testing

  - name: install Percona Server 5.7 packages
    include_tasks: ../tasks/install_ps57.yml

  - name: install Percona Toolkit new deb packages
    include_tasks: ../tasks/install_pt.yml

  - name: install sysbench packages
    include_tasks: ../tasks/install_sysbench.yml
    when: lookup('env', 'install_repo') != "experimental"

  - name: install Percona XtraBackup 2.4 packages
    include_tasks: ../tasks/install_pxb24.yml

  - name: list installed packages
    include_tasks: ../tasks/list_installed_packages.yml

  - name: start mysql service with service command
    command: service mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mysql service with systemctl command
    command: systemctl start mysql
    when: (ansible_distribution == "Amazon") or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7")

  - name: run mysql_upgrade
    command: mysql_upgrade -uroot

  - name: restart mysql service
    service: name=mysql state=restarted

  - name: keyring plugins test
    command: /package-testing/scripts/ps_keyring_plugins_test/ps_keyring_plugins_test.sh ps57

  - name: run ps_admin to install rocksdb
    command: /usr/bin/ps-admin --enable-rocksdb

  - name: check that Percona Server version is correct
    command: /package-testing/version_check.sh ps57

  - name: check that Percona Server package versions are correct
    command: /package-testing/package_check.sh ps57

  - name: check that Percona Toolkit version is correct
    command: /package-testing/version_check.sh pt
    when: lookup('env', 'install_repo') != "experimental"

# - name: check that sysbench version is correct
#   command: /package-testing/version_check.sh sysbench
#   when: lookup('env', 'install_repo') != "experimental"

  - name: check that Percona XtraBackup version is correct
    command: /package-testing/version_check.sh pxb24
    when: lookup('env', 'install_repo') != "experimental"

  - name: check that Percona XtraBackup package versions are correct
    command: /package-testing/package_check.sh pxb24
    when: lookup('env', 'install_repo') != "experimental"

  - name: remove PS 5.7 packages
    include_tasks: ../tasks/remove_ps57.yml

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000
