---
# This playbook does following:
#   installs latest version of PS 5.7, PT and PXB 2.4
#   upgrades to PS 8.0

# Cosmic is still missing python
# import_playbook: test_prep.yml
- import_playbook: common_57.yml

- hosts: all
  become: true
  become_method: sudo
  vars:
    vault_token: "{{ lookup('env', 'VAULT_TEST_TOKEN') }}"
    vault_cert: "{{ lookup('env', 'VAULT_TEST_CERT') }}"

  tasks:
  - name: remove PS 5.7 packages
    include_tasks: ../tasks/remove_ps57.yml

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000

  - name: copy config file to original location
    copy:
      src: /etc/my.cnf.backup
      dest: /etc/my.cnf
      remote_src: yes
      force: yes
    when: (ansible_distribution == "Amazon") or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7")

  - name: restore percona-server.conf.d and mysql.cnf.d
    shell: |
      mv /etc/percona-server.conf.d_backup-* /etc/percona-server.conf.d
      mv /etc/my.cnf.d_backup-* /etc/my.cnf.d
    when: (ansible_distribution == "Amazon") or (ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7")

  - name: remove PXB 2.4 packages
    include_tasks: ../tasks/remove_pxb24.yml

  - name: remove mysql package on centos 8
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - mysql
      - mysql-common
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - name: include tasks for enabling PS 8 test repo
    include: ../tasks/enable_ps8_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling PS 8 test repo
    include: ../tasks/enable_ps8_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling PS 8 experimental repo
    include: ../tasks/enable_ps8_experimental_repo.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: enable tools testing repo
    command: percona-release enable tools testing

  - name: install Percona Toolkit new deb packages
    include_tasks: ../tasks/install_pt.yml

  - name: install Percona Server 8.0 packages
    include_tasks: ../tasks/install_ps80.yml

  - name: install sysbench new deb packages
    include_tasks: ../tasks/install_sysbench.yml
    when: lookup('env', 'install_repo') != "experimental"

  - name: install Percona XtraBackup 8.0 packages
    include_tasks: ../tasks/install_pxb80.yml
    when: lookup('env', 'install_repo') != "experimental"

  - name: install percona-mysql-shell package
    include_tasks: ../tasks/install_pshell.yml

  - name: list installed packages
    include_tasks: ../tasks/list_installed_packages.yml

  - name: start mysql service
    service: name=mysql state=started

  - name: check that Percona Server version is correct
    command: /package-testing/version_check.sh ps80

  - name: check that Percona Server package versions are correct
    command: /package-testing/package_check.sh ps80

  - name: keyring plugins test
    command: /package-testing/scripts/ps_keyring_plugins_test/ps_keyring_plugins_test.sh ps80
    when: lookup('env', 'PS_SKIP_KEYRING') == "" or lookup('env', 'PS_SKIP_KEYRING') == "0"

  - name: run Group Replication tests
    include_tasks: ../tasks/gr_test.yml

  - name: remove PS 8.0 packages
    include_tasks: ../tasks/remove_ps80.yml

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - name: check /var/lib/mysql exists and not empty
    fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000
