---
# This playbook does following:
#   enables Percona testing repository
#   installs the latest version of PMM2 client
#   does some tests

- hosts: all
  become: true
  become_method: sudo
  vars:
    pmm_server_address: "{{ lookup('env', 'PMM_SERVER_IP') }}"
    test_repo: "{{ lookup('env', 'install_repo') }}"
    metrics_mode: "{{ lookup('env', 'METRICS_MODE') }}"
    pmm_version: "{{ lookup('env', 'PMM_VERSION') | regex_search('\\S(.*\\S)?') }}"

  tasks:
  - name: Register Instance IP
    shell: echo $(ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')
    register: instance_ip

  - name: Register Instance IP as a variable
    set_fact:
      instance_ip: "{{ instance_ip.stdout }}"

  - name: include tasks for test env setup
    include_tasks: ../tasks/pmm2_client_test_prepare.yml

  - name: install PMM client new deb packages
    apt: name=pmm2-client update_cache=yes state=latest
    when: ansible_os_family == "Debian"

  - name: install PMM client new rpm packages
    yum: name=pmm2-client state=latest
    when: ansible_os_family == "RedHat"

  - name: check that PMM Client version is correct
    include_tasks: ../tasks/verify_pmm_client_version.yml

  - name: configure pmm client to connect to server in push/auto Mode
    shell: pmm-admin config --force --server-insecure-tls --metrics-mode=auto --server-url=https://admin:admin@{{ pmm_server_address }} {{ instance_ip }} generic node_{{ instance_ip }}
    when: lookup('env', 'metrics_mode') == "push" or lookup('env', 'metrics_mode') == ""

  - name: configure pmm client to connect to server in pull Mode
    shell: pmm-admin config --force --server-insecure-tls --metrics-mode=pull --server-url=https://admin:admin@{{ pmm_server_address }} {{ instance_ip }} generic node_{{ instance_ip }}
    when: lookup('env', 'metrics_mode') == "pull"

### start PS 5.7
  - name: install and start Percona Server 5.7
    include_tasks: ../tasks/start_ps57.yml

  - name: check if Metric End point with Auth works for Mysqld Exporter
    shell: "{{item}}"
    with_items:
      - "bash -x ../scripts/pmm2_check_metric.sh --service_name mysql_{{ instance_ip }} --metric_name mysql_up --pmm_server_ip {{pmm_server_address}} --agent_type mysqld_exporter --metric_value 1"
## end PS

### start PSMDB 4.4
  - name: install and start Percona Server MongoDB 4.4
    include_tasks: ../tasks/start_psmdb44.yml

  - name: check if Metric End point with Auth works for MongoDB Exporter
    shell: "{{item}}"
    with_items:
      - "bash -x ../scripts/pmm2_check_metric.sh --service_name mongodb_{{ instance_ip }} --metric_name mongodb_up --pmm_server_ip {{pmm_server_address}} --agent_type mongodb_exporter --metric_value 1"

  - name: check if Metric End point with Auth works for MongoDB Exporter for service with socket
    shell: "{{item}}"
    with_items:
      - "bash -x ../scripts/pmm2_check_metric.sh --service_name mongodb_socket_{{ instance_ip }} --metric_name mongodb_up --pmm_server_ip {{pmm_server_address}} --agent_type mongodb_exporter --metric_value 1"

  - name: remove mongodb service from monitoring which was added via socket
    command: pmm-admin remove mongodb mongodb_socket_{{ instance_ip }}

### end PSMDB

### start pgsql 13
  - name: install and start Percona Server MongoDB 4.4
    include_tasks: ../tasks/start_psql13.yml

  - name: check if Metric End point with Auth works for Postgres Exporter
    shell: "{{item}}"
    retries: 3
    delay: 10
    with_items:
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.hr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.lr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.mr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_{{ instance_ip }} --metric_name pg_up{collector=\"\exporter\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1

  - name: check if Metric End point with Auth works for Postgres Exporter when service added via socket
    shell: "{{item}}"
    retries: 3
    delay: 10
    with_items:
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_socket_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.hr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_socket_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.lr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_socket_{{ instance_ip }} --metric_name pg_up{collector=\"\custom_query.mr\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1
      - bash -x ../scripts/pmm2_check_metric.sh --service_name pgsql_socket_{{ instance_ip }} --metric_name pg_up{collector=\"\exporter\"\} --pmm_server_ip {{pmm_server_address}} --agent_type postgres_exporter --metric_value 1

  - name: remove postgresql instances added via socket
    command: pmm-admin remove postgresql pgsql_socket_{{ instance_ip }}
### end PG

  - name: parse and set PMM minor version
    shell: "pmm-admin --version | grep -oP '(?<=[.])\\w+(?=[.])' | head -1"
    register: pmm_agent_minor_version

  - name: include Exporters Port in output checks for 2.29.0+
    include_tasks: ../tasks/exporter-port-output-checks.yml
    when: pmm_agent_minor_version.stdout | int >= 29
    with_items:
      - vmagent
      - node_exporter
      - postgres_exporter
      - mongodb_exporter
      - mysqld_exporter

  - name: check if pmm_agent is connected
    shell: pmm-admin list | grep pmm_agent | awk -F" " '{print $2}'
    register: pmm_agent_status

  - name: Assert if the pmm-admin list contains pmm_agent type and Connected
    assert:
     that:
      - "'Connected' in pmm_agent_status.stdout"

  - name: Wait for node_exporter to be Running Status.
    shell: pmm-admin list | grep node_exporter | awk -F" " '{print $2}'
    register: ne_status
    until: ne_status.stdout.find('Running') != -1
    delay: 5
    retries: 5

  - name: check if node_exporter is Running
    shell: pmm-admin list | grep node_exporter | awk -F" " '{print $2}'
    register: node_exporter_status

  - name: check if Metric End point with Auth works for Node Exporter
    shell: "{{item}}"
    retries: 3
    delay: 10
    with_items:
      - "bash -x ../scripts/pmm2_check_metric.sh --metric_name node_textfile_scrape_error --pmm_server_ip {{pmm_server_address}} --agent_type node_exporter --metric_value 0"

  - name: Print the node_exporter_status
    ansible.builtin.debug:
      msg: Node Exporter Status is {{ node_exporter_status.stdout }}

  - name: Assert if the pmm-admin list contains node_exporter and Running state
    assert:
     that:
      - "'Running' in node_exporter_status.stdout"

  - name: Wait for vmagent to be Running Status.
    shell: pmm-admin list | grep vmagent | awk -F" " '{print $2}'
    register: vm_status
    until: vm_status.stdout.find('Running') != -1
    delay: 5
    retries: 5

  - name: check if vmagent is Running
    shell: pmm-admin list | grep vmagent | awk -F" " '{print $2}'
    register: vmagent_status

  - name: Print the vmagent Status
    ansible.builtin.debug:
      msg: vmagent status is {{ vmagent_status.stdout }}

  - name: Assert if the pmm-admin list contains vmagent and Running State
    assert:
     that:
      - "'Running' in vmagent_status.stdout"

  - name: check if postgresql_pgstatements_agent is Running
    shell: pmm-admin list | grep postgresql_pgstatements_agent | awk -F" " '{print $2}'
    register: postgresql_pgstatements_agent

  - name: Print the postgresql_pgstatements_agent Status
    ansible.builtin.debug:
      msg: postgresql_pgstatements_agent status is {{ postgresql_pgstatements_agent.stdout }}

  - name: Assert if the pmm-admin list contains postgresql_pgstatements_agent and Running State
    assert:
     that:
      - "'Running' in postgresql_pgstatements_agent.stdout"

  - name: check that PMM client version is correct
    include_tasks: ../tasks/verify_pmm_status_versions.yml

  - name: check pmm2-client files
    include_tasks: ../tasks/verify_pmm_client_files.yml

  - name: Print the pmm-admin list value
    ansible.builtin.debug:
      msg: System {{ list_output.stdout }}

  - name: Assert if the pmm-admin list contains postgreSQL instance
    assert:
      that:
        - "'PostgreSQL' in list_output.stdout"

  - name: Wait for postgres_exporter to have Running Status.
    shell: pmm-admin list | grep 'postgres_exporter' | awk -F" " '{print $2}'
    register: postgres_exporter_status
    until: postgres_exporter_status.stdout.find('Running') != -1
    delay: 5
    retries: 5
