# This playbook install Percona Server 5.7 with TokuDB and MyRocks
# It will disable the original repo and upgrade to Percona Server 8.0
#

- import_playbook: ../playbooks/common_57.yml

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Remove PS 5.7 packages
  - include_tasks: ../tasks/remove_ps57.yml

  - name: include tasks for enabling PS 8 test repo
    include: ../tasks/enable_ps8_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling PS 8 test repo
    include: ../tasks/enable_ps8_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""
