# This playbook install Percona Server 5.7 with TokuDB and MyRocsk
# It will disable the original repo and upgrade to Percona Server 8.0
#

  - import_playbook: ../playbooks/common_57.yml
  - import_playbook: ../playbooks/ps_80.yml
