---
# This playbook does following:
#   enables Percona testing repository
#   installs PSMDB 3.6
#   does some tests
- import_playbook: test_prep.yml

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: include tasks for enabling test repo
    include_tasks: ../tasks/enable_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling main repo
    include_tasks: ../tasks/enable_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling experimental repo
    include_tasks: ../tasks/enable_experimental_repo.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: install Percona Server for MongoDB 3.6 new rpm packages
    include_tasks: ../tasks/install_psmdb_36.yml

  - name: start mongod with service
    command: service mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mongod with systemctl
    command: systemctl start mongod
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: check that PSMDB 3.6 package versions are correct
    command: /package-testing/package_check.sh psmdb36

  - name: test perconadecrypt
    command: /package-testing/scripts/psmdb_encryption/perconadecrypt-test.sh 3.6 keyfile

  - name: test SE change, import data, restart service
    command: /package-testing/scripts/psmdb_test.sh 3.6

  - name: set pass and enable auth
    command: /package-testing/scripts/psmdb_set_auth.sh

  - name: run bats tests for mongo init scripts
    command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats

  - name: install numactl package
    include_tasks: ../tasks/install_numactl.yml

  - name: run bats tests for mongo init scripts after numactl install
    command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats

  - name: start mongod service
    service: name=mongod state=started

  - name: remove Percona Server for MongoDB 3.6 deb packages
    apt: 
      name: "{{ packages }}"
      update_cache: no
      state: absent
    vars:
      packages:
      - percona-server-mongodb-36-server
    when: ansible_os_family == "Debian"

  - name: remove Percona Server for MongoDB 3.6 rpm packages
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - Percona-Server-MongoDB-36-server
    when: ansible_os_family == "RedHat"

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mongodb stopped
