- hosts: all
  become: true
  become_method: sudo

  tasks:
- name: include tasks for test env setup
    include: ../tasks/test_prep.yml

- name: include tasks for enabling main repo
    include: ../tasks/enable_main_repo.yml

- name: list installed packages
    include_tasks: ../tasks/list_installed_packages.yml

- name: include tasks for enabling testing repo
    include: ../tasks/enable_testing_repo.yml

- name: install Percona Server deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-release
    when: ansible_os_family == "Debian"

  - name: install Percona Server rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      disablerepo: "epel"
      update_cache: yes
    vars:
      packages:
      - percona-release
    when: ansible_os_family == "RedHat"
    
- name: list installed packages
    include_tasks: ../tasks/list_installed_packages.yml

- name: check that Percona Server package versions are correct
    command: /package-testing/package_check.sh repo
