---
# This playbook can be used to setup machine for running tests and ansible
# Therefore gathering of the facts is disabled

- hosts: all
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
  - name: install python2
    raw: test -e /usr/bin/python || (which apt && apt -y update && apt install -y python-minimal)
    when: ansible_os_family == "Debian"
  - name: Install python2 for Ansible rhel based distros
    raw: test -e /usr/bin/python || (yum update -y && yum install -y python-minimal python-libselinux)
    become: true
    changed_when: false
    when: ansible_os_family == "RedHat"
