---
  - name: include tasks for test env setup
    include_tasks: ../../../tasks/test_prep.yml

  - name: install libev rpm package
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - libev
    when: ansible_os_family == "RedHat"

  - name: include tasks for enabling main repo
    include_tasks: ../../../tasks/enable_main_repo.yml
 
  - name: include tasks for enabling PS 8 test repo
    include_tasks: ../../../tasks/enable_ps8_main_repo.yml

  - name: download and extract world database
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

  - name: install Percona Server 8.0 packages
    include_tasks: ../../../tasks/install_ps80.yml

  - name: Download install and check Percona XtraBackup 8.0 normal tarball from downloads area
    command: /package-testing/download_pxb_binary_tarball.sh pxb80 main normal
    environment:
      PXB_VERSION: "{{ lookup('env', 'PXB_VERSION') }}"

  - name: start mysql service with systemctl command
    command: systemctl start mysql

  - name: set root password on centos
    command: /package-testing/setpass_57.sh
    when: ansible_os_family == "RedHat"

  - name: install plugins, import world database
    command: /package-testing/plugins_test.sh

  - name: run backup for Redhat/Centos
    command: pxb80/bin/xtrabackup --backup --user=root --target-dir=/tmp/backups/ --socket=/var/lib/mysql/mysql.sock

  - name: prepare backup
    command: pxb80/bin/xtrabackup --prepare --target-dir=/tmp/backups/

  - name: run backup for Redhat/Centos with streaming and encryption enabled
    shell: pxb80/bin/xtrabackup --backup --user=root --target-dir=backups/ --socket=/var/lib/mysql/mysql.sock --encrypt=AES256 --encrypt-key=mAU3Xs5sRcSB7zBEJP1BInPP5lgShKly --stream=xbstream --parallel=10 > backup.stream

  - name: extract and decrypt backup
    shell: pxb80/bin/xbstream --directory=backups/ --extract --decrypt=AES256 --encrypt-key=mAU3Xs5sRcSB7zBEJP1BInPP5lgShKly < backup.stream

  - name: prepare backup
    command: pxb80/bin/xtrabackup --prepare --target-dir=backups/

  - name: remove backup files
    command: rm -r pxb80 backups /tmp/backups

  - name: Download install and check Percona XtraBackup 8.0 minimal tarball from downloads area
    command: /package-testing/download_pxb_binary_tarball.sh pxb80 main minimal

  - name: run backup for Redhat/Centos
    command: pxb80/bin/xtrabackup --backup --user=root --target-dir=/tmp/backups/ --socket=/var/lib/mysql/mysql.sock

  - name: prepare backup
    command: pxb80/bin/xtrabackup --prepare --target-dir=/tmp/backups/

  - name: run backup for Redhat/Centos with streaming and encryption enabled
    shell: pxb80/bin/xtrabackup --backup --user=root --target-dir=backups/ --socket=/var/lib/mysql/mysql.sock --encrypt=AES256 --encrypt-key=mAU3Xs5sRcSB7zBEJP1BInPP5lgShKly --stream=xbstream --parallel=10 > backup.stream

  - name: extract and decrypt backup
    shell: pxb80/bin/xbstream --directory=backups/ --extract --decrypt=AES256 --encrypt-key=mAU3Xs5sRcSB7zBEJP1BInPP5lgShKly < backup.stream

  - name: prepare backup
    command: pxb80/bin/xtrabackup --prepare --target-dir=backups/
