---
- name: Prepare node for running tests
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
#    - name: setup epel 6 repo
#      yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
#      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
#
#    - name: setup epel 7 repo
#      yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
#      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
#
#    - name: setup epel 7 repo for Amazon Linux 2
#      yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
#      when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
#
    - name: setup epel 8 repo
      yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm state=present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

    - name: setup ca-certificates release
      yum:
        name: ca-certificates
        update_cache: yes
        state: present
      when: ansible_os_family == "RedHat"

    - name: setup epel release
      yum:
        name: epel-release
        update_cache: yes
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version != "8"

    - name: fix jessie repos
      template: src=../templates/jessie.repo
                dest=/etc/apt/sources.list
                mode=0640 owner=root group=root
      when: ansible_os_family == "Debian" and ansible_distribution_release == "jessie"

    - name: fix backports repo on jessie in aws image
      file:
        path: /etc/apt/sources.list.d/backports.list
        state: absent
      when: ansible_os_family == "Debian" and ansible_distribution_release == "jessie"

    - name: install needed packages for running tests with apt
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
          - unzip
          - wget
          - gnupg
          - gnupg2
          - rsync
          - acl
      retries: 60
      delay: 10
      register: result
      until: result is not failed
      when: ansible_os_family == "Debian"

    - name: update systemd-sysv integration on debian/ubuntu
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - systemd-sysv
      when: ansible_os_family == "Debian" and ansible_distribution_release != "trusty"

    - name: install needed packages for running tests with yum
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - pv
          - libselinux-python
          - unzip
          - wget
          - rsync
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 7

    - name: install needed packages for running tests with yum on RHEL8
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - unzip
        - wget
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8

    - name: download package-testing repo with wget
      command: "{{ item }}"
      with_items:
        - wget --no-check-certificate -O master.zip https://github.com/Percona-QA/package-testing/archive/master.zip
        - unzip master.zip
        - rm -f master.zip
        - mv package-testing-master /package-testing

    - name: install latest bats from github
      command: "{{ item }}"
      with_items:
        - rm -f master.zip
        - wget --no-check-certificate -O master.zip https://github.com/sstephenson/bats/archive/master.zip
        - unzip master.zip
        - rm -f master.zip
        - bats-master/install.sh /usr/local
        - rm -rf bats-master

    - name: get list of installed packages on Debian/Ubuntu
      shell: dpkg -l|grep -iE "percona|sysbench|mysql|mongo|proxysql|maria" || true
      register: installed_packages
      when: ansible_os_family == "Debian"

    - name: list installed packages on Debian/Ubuntu
      debug:
        var: installed_packages
      when: ansible_os_family == "Debian"

    - name: get list of installed packages on Centos
      shell: yum list installed|grep -iE "percona|sysbench|mysql|mongo|proxysql|maria" || true
      register: installed_packages
      when: ansible_os_family == "RedHat"

    - name: list installed packages on Centos
      debug:
        var: installed_packages
      when: ansible_os_family == "RedHat"

    - name: get selinux status
      command: sestatus
      register: selinux_status
      when: ansible_os_family == "RedHat"

    - name: list selinux status
      debug:
        var: selinux_status
      when: ansible_os_family == "RedHat"

    - name: get list of enabled dnf modules on centos 8
      command: dnf module list --enabled
      register: enabled_dnf_modules
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

    - name: list enabled dnf modules on centos 8
      debug:
        var: enabled_dnf_modules
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
