---
name: Package Test Matrix

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      package_testing_branch:
        description: 'Target branch for package-testing repository'
        type: string
        default: 'master'
        required: true
      repository:
        description: 'Select Repo for Client:'
        required: true
        default: 'dev-latest'
        type: choice
        options:
          - release
          - release candidate
          - dev-latest
      metrics_mode:
        description: 'Select the Metrics Mode for PMM Client:'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - push
          - pull

jobs:
  get_versions:
    name: Get versions
    uses: percona/pmm-ui-tests/.github/workflows/pmm-version-getter.yml@main
    with:
      repository: ${{ inputs.repository || 'dev-latest' }}

  i_test:
    name: "pmm2-client_integration"
    uses: ./.github/workflows/pmm-package-test-runner.yml
    secrets: inherit
    needs: get_versions
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.get_versions.outputs.pt_os) }}
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      expected_version: ${{needs.get_versions.outputs.finish_version}}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration"
      test_name: ${{ matrix.os }}
      os: ${{ matrix.os }}

  u_test:
    name: "pmm2-client_integration_upgrade"
    uses: ./.github/workflows/pmm-package-test-runner.yml
    secrets: inherit
    needs: get_versions
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.get_versions.outputs.pt_os) }}
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      expected_version: ${{needs.get_versions.outputs.finish_version}}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration_upgrade"
      test_name: ${{ matrix.os }}
      os: ${{ matrix.os }}

  t_test:
    name: "pmm2-client_integration_upgrade_custom_path"
    uses: ./.github/workflows/pmm-package-test-runner.yml
    secrets: inherit
    needs: get_versions
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.get_versions.outputs.pt_os) }}
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      expected_version: ${{needs.get_versions.outputs.finish_version}}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration_upgrade_custom_path"
      test_name: ${{ matrix.os }}
      os: ${{ matrix.os }}
