---
name: Package Test Matrix(full)

on:
  workflow_dispatch:
    inputs:
      package_testing_branch:
        description: 'Target branch for package-testing repository'
        type: string
        default: 'master'
        required: true
      repository:
        description: 'Select Repo for Client:'
        required: true
        default: 'dev-latest'
        type: choice
        options:
          - release
          - release candidate
          - dev-latest
      metrics_mode:
        description: 'Select the Metrics Mode for PMM Client:'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - push
          - pull

jobs:
  c_test:
    name: "pmm2-client"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration"

  cu_test:
    name: "pmm2-client_upgrade"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_upgrade"

  tb_test:
    name: "pmm2-client_custom_path"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_custom_path"

  auth_config_test:
    name: "pmm2-client_integration_auth_config"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration_auth_config"

  auth_register_test:
    name: "pmm2-client_integration_auth_register"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration_auth_register"

  auth_setup_test:
    name: "pmm2-client_integration_auth_setup"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration_auth_setup"

  tbi_test:
    name: "pmm2-client_integration_custom_path"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration_custom_path"

  port_test:
    name: "pmm2-client_integration_custom_port"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration_custom_port"

  port_u_test:
    name: "pmm2-client_integration_upgrade_custom_port"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration_upgrade_custom_port"

  i_test:
    name: "pmm2-client_integration"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration"

  iu_test:
    name: "pmm2-client_integration_upgrade"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration_upgrade"

  tu_test:
    name: "pmm2-client_integration_upgrade_custom_path"
    uses: ./.github/workflows/pmm-package-test-single.yml
    secrets: inherit
    with:
      package_testing_branch: ${{ inputs.package_testing_branch || 'master' }}
      repository: ${{ inputs.repository || 'dev-latest' }}
      metrics_mode: ${{ inputs.metrics_mode || 'auto' }}
      playbook: "pmm2-client_integration_upgrade_custom_path"
